config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"

   root :to => 'welcome#index'

   resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :title
  validates :text, :title, presence: true, :length => { :minimum => 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index 
		@allPosts = Post.all
	end

	def new
	end

	def create
	  @post = Post.new(params[:post])
	 
	  if @post.save
	  	redirect_to @post
	  else
	  	render 'new'
	  end

	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update 
		@post = Post.find(params[:id])

		if @post.update_attributes(params[:post])
			redirect_to @post
		else
			render 'edit'
		end
	end
	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= form_for :post, url: post_path(@post.id), method: :put do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>All posts</h1>

<table>

<% @allPosts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.text %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New post', new_post_path %>
<%= link_to("Home", { :controller => 'welcome', :action => 'index'}) %>

app/views/posts/new.html.erb
<h1> Please, fill in the form! </h1>

<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.text %></p>

<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>Welcome to my first rails app!</h1>
<p>Posts resource is already defined</p>

<p>Here's the actions you're able to use:</p>
<ul>
	<li><%= link_to("Show all posts", { :controller => 'posts', :action => 'index'}) %></li>
	<li><%= link_to("Create a new post", { :controller => 'posts', :action => 'new'}) %></li>
</ul>